spring:
  application:
    name: habit_tracker
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/habit_tracker}
    username:  ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:nhatcoi123}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET_KEY:hTQTdTxhQD9Jx12CCdB3ynJOHdCzeQzVx8MI0HwTqFcY0rPw9AmzQmElutWe8y19}
  expiration: 2592000000
  access-token-expiration: 1800000

url:
  web: http://localhost:5173

firebase:
  service-account-path: "jtracker-adminsdk.json"