spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/habit_tracker}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:nhatcoi123}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: ${JWT_SECRET_KEY:mysecretkeymysecretkeymysecretkeymysecretkeymysecretkey}

firebase:
  service-account-path: "jtracker-adminsdk.json"

