spring:
  application:
    name: habit_tracker
  profiles:
    active: dev

server:
  port: 8081

jwt:
  expiration: 2592000000
  access-token-expiration: 259200000

url:
  web: "https://jtracker-react.vercel.app"

