services:
  db:
    image: jackie2006/postgres:14.15-alpine3.21
    container_name: postgres-2
    env_file:
      - .env
    volumes:
      - postgres-old-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - backend-2
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgresdb" ]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always

  be:
    container_name: Jtracker
    build:
      context: .
      dockerfile: Dockerfile
    image: jtracker:0.0.1
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - backend-2


volumes:
  postgres-old-volume:
    external: true
    name: 40112f4fc0ee694043967885caa46874548d97af2ac31459f1396ccfb715e52b

networks:
  backend-2:
    driver: bridge


