#name: Build and Deploy React App
#
#on:
#  push:
#    paths:
#        - 'FE/**'
#    branches:
#      - main
#
#jobs:
#  build:
#    runs-on: ubuntu-22.04
#    steps:
#      - uses: actions/checkout@v4
#      - name: Install dependencies
#        run: |
#          cd frontend
#          npm install
#      - name: Build the app
#        run: |
#          cd frontend
#          npm run build


## FE has been deployed by Vercel